name: Check for .env files

on: [push, pull_request]

jobs:
  check-env-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Ensure no .env files are committed
        run: |
          if git ls-files | grep '.env'; then
            echo ".env file found, please remove it!";
            exit 1;
          fi
